export const schemaTypes = [
  {
    name: 'hero',
    title: 'Hero',
    type: 'document',
    fields: [
      { name: 'eyebrow', title: 'Eyebrow', type: 'string' },
      { name: 'heading', title: 'Heading', type: 'string', validation: (Rule: any) => Rule.required() },
      { name: 'subtitle', title: 'Subtitle', type: 'text' },
      { name: 'buttonText', title: 'Button Text', type: 'string' },
      { name: 'buttonLink', title: 'Button Link', type: 'string' },
      { name: 'secondaryButtonText', title: 'Secondary Button Text', type: 'string' },
      { name: 'secondaryButtonLink', title: 'Secondary Button Link', type: 'string' },
      {
        name: 'image',
        title: 'Image',
        type: 'image',
        options: { hotspot: true },
        fields: [{ name: 'alt', title: 'Alt Text', type: 'string' }],
      },
      { name: 'sortOrder', title: 'Sort Order', type: 'number' },
    ],
  },
  {
    name: 'category',
    title: 'Category',
    type: 'document',
    fields: [
      { name: 'title', title: 'Title', type: 'string', validation: (Rule: any) => Rule.required() },
      { name: 'titleAm', title: 'Title (Amharic)', type: 'string' },
      { name: 'slug', title: 'Slug', type: 'slug', options: { source: 'title' } },
      { name: 'description', title: 'Description', type: 'text' },
      { name: 'descriptionAm', title: 'Description (Amharic)', type: 'text' },
      { name: 'sortOrder', title: 'Sort Order', type: 'number' },
      { name: 'hidden', title: 'Hidden', type: 'boolean', initialValue: false },
    ],
  },
  {
    name: 'product',
    title: 'Product',
    type: 'document',
    fields: [
      { name: 'name', title: 'Name', type: 'string', validation: (Rule: any) => Rule.required() },
      { name: 'nameAm', title: 'Name (Amharic)', type: 'string' },
      { name: 'slug', title: 'Slug', type: 'slug', options: { source: 'name' } },
      { name: 'category', title: 'Category', type: 'reference', to: [{ type: 'category' }] },
      { name: 'categoryName', title: 'Category Name Fallback', type: 'string' },
      { name: 'description', title: 'Description', type: 'text' },
      { name: 'descriptionAm', title: 'Description (Amharic)', type: 'text' },
      { name: 'priceBirr', title: 'Price (ETB)', type: 'number', validation: (Rule: any) => Rule.min(0) },
      { name: 'priceUsd', title: 'Price (USD)', type: 'number', validation: (Rule: any) => Rule.min(0) },
      {
        name: 'featuredImage',
        title: 'Featured Image',
        type: 'image',
        options: { hotspot: true },
        fields: [{ name: 'alt', title: 'Alt Text', type: 'string' }],
      },
      {
        name: 'images',
        title: 'Additional Images',
        type: 'array',
        of: [
          {
            type: 'image',
            options: { hotspot: true },
            fields: [{ name: 'alt', title: 'Alt Text', type: 'string' }],
          },
        ],
      },
      { name: 'availability', title: 'Available', type: 'boolean', initialValue: true },
      { name: 'bestSeller', title: 'Best Seller', type: 'boolean', initialValue: false },
      { name: 'sortOrder', title: 'Sort Order', type: 'number' },
      { name: 'createdDate', title: 'Created Date', type: 'datetime' },
      { name: 'updatedDate', title: 'Updated Date', type: 'datetime' },
    ],
  },
  {
    name: 'order',
    title: 'Order',
    type: 'document',
    fields: [
      { name: 'orderId', title: 'Order ID', type: 'string' },
      { name: 'customerName', title: 'Customer Name', type: 'string' },
      { name: 'phone', title: 'Phone', type: 'string' },
      { name: 'email', title: 'Email', type: 'string' },
      { name: 'address', title: 'Delivery Address', type: 'text' },
      { name: 'notes', title: 'Notes', type: 'text' },
      {
        name: 'items',
        title: 'Ordered Products',
        type: 'array',
        of: [
          {
            type: 'object',
            fields: [
              { name: 'productId', title: 'Product ID', type: 'string' },
              { name: 'name', title: 'Product Name', type: 'string' },
              { name: 'category', title: 'Category', type: 'string' },
              { name: 'quantity', title: 'Quantity', type: 'number' },
              { name: 'priceBirr', title: 'Unit Price (ETB)', type: 'number' },
              { name: 'priceUsd', title: 'Unit Price (USD)', type: 'number' },
              { name: 'subtotalBirr', title: 'Subtotal (ETB)', type: 'number' },
              { name: 'subtotalUsd', title: 'Subtotal (USD)', type: 'number' },
              { name: 'image', title: 'Product Image URL', type: 'url' },
            ],
          },
        ],
      },
      { name: 'subtotalBirr', title: 'Subtotal (ETB)', type: 'number' },
      { name: 'subtotalUsd', title: 'Subtotal (USD)', type: 'number' },
      { name: 'deliveryFeeBirr', title: 'Delivery Fee (ETB)', type: 'number' },
      { name: 'totalBirr', title: 'Total (ETB)', type: 'number' },
      { name: 'totalUsd', title: 'Total (USD)', type: 'number' },
      { name: 'timestamp', title: 'Timestamp', type: 'datetime' },
      {
        name: 'status',
        title: 'Status',
        type: 'string',
        options: { list: ['Pending', 'Confirmed', 'Completed', 'Cancelled'] },
        initialValue: 'Pending',
      },
    ],
  },
  {
    name: 'customOrder',
    title: 'Custom Order',
    type: 'document',
    fields: [
      { name: 'requestId', title: 'Request ID', type: 'string' },
      { name: 'name', title: 'Customer Name', type: 'string' },
      { name: 'phone', title: 'Phone', type: 'string' },
      { name: 'email', title: 'Email', type: 'string' },
      { name: 'productType', title: 'Product Type', type: 'string' },
      { name: 'occasion', title: 'Occasion', type: 'string' },
      { name: 'colors', title: 'Preferred Colors', type: 'string' },
      { name: 'size', title: 'Size / Measurements', type: 'string' },
      { name: 'deadline', title: 'Deadline', type: 'date' },
      { name: 'message', title: 'Message', type: 'text' },
      {
        name: 'sampleImages',
        title: 'Sample Images',
        type: 'array',
        of: [
          {
            type: 'image',
            options: { hotspot: true },
            fields: [{ name: 'alt', title: 'Alt Text', type: 'string' }],
          },
        ],
      },
      { name: 'timestamp', title: 'Timestamp', type: 'datetime' },
      {
        name: 'status',
        title: 'Status',
        type: 'string',
        options: { list: ['Pending', 'Confirmed', 'Completed', 'Cancelled'] },
        initialValue: 'Pending',
      },
    ],
  },
  {
    name: 'galleryCategory',
    title: 'Gallery Category',
    type: 'document',
    fields: [
      { name: 'title', title: 'Title', type: 'string', validation: (Rule: any) => Rule.required() },
      { name: 'slug', title: 'Slug', type: 'slug', options: { source: 'title' } },
      { name: 'sortOrder', title: 'Sort Order', type: 'number' },
      { name: 'hidden', title: 'Hidden', type: 'boolean', initialValue: false },
    ],
  },
  {
    name: 'galleryItem',
    title: 'Gallery Item',
    type: 'document',
    fields: [
      { name: 'title', title: 'Title', type: 'string' },
      { name: 'titleAm', title: 'Title (Amharic)', type: 'string' },
      { name: 'caption', title: 'Caption', type: 'text' },
      { name: 'captionAm', title: 'Caption (Amharic)', type: 'text' },
      { name: 'alt', title: 'Alt Text', type: 'string' },
      { name: 'category', title: 'Display Category', type: 'string' },
      {
        name: 'filter',
        title: 'Filter',
        type: 'string',
        options: { list: ['All', 'Dresses', 'Scarves', 'Weddings', 'Children', 'Home Textiles', 'Workshop'] },
      },
      { name: 'image', title: 'Image', type: 'image', options: { hotspot: true } },
      { name: 'tall', title: 'Tall Layout', type: 'boolean' },
      { name: 'sortOrder', title: 'Sort Order', type: 'number' },
    ],
  },
  {
    name: 'homepage',
    title: 'Homepage',
    type: 'document',
    fields: [
      {
        name: 'hero',
        title: 'Hero',
        type: 'object',
        fields: [
          { name: 'eyebrow', title: 'Eyebrow', type: 'string' },
          { name: 'heading', title: 'Heading', type: 'string' },
          { name: 'subtitle', title: 'Subtitle', type: 'text' },
          { name: 'buttonText', title: 'Button Text', type: 'string' },
          { name: 'buttonLink', title: 'Button Link', type: 'string' },
          { name: 'secondaryButtonText', title: 'Secondary Button Text', type: 'string' },
          { name: 'secondaryButtonLink', title: 'Secondary Button Link', type: 'string' },
          { name: 'image', title: 'Image', type: 'image', options: { hotspot: true }, fields: [{ name: 'alt', title: 'Alt Text', type: 'string' }] },
        ],
      },
      {
        name: 'heroAm',
        title: 'Hero (Amharic)',
        type: 'object',
        fields: [
          { name: 'eyebrow', title: 'Eyebrow', type: 'string' },
          { name: 'heading', title: 'Heading', type: 'string' },
          { name: 'subtitle', title: 'Subtitle', type: 'text' },
          { name: 'buttonText', title: 'Button Text', type: 'string' },
          { name: 'secondaryButtonText', title: 'Secondary Button Text', type: 'string' },
        ],
      },
      { name: 'heritageEyebrow', title: 'Heritage Eyebrow', type: 'string' },
      { name: 'heritageEyebrowAm', title: 'Heritage Eyebrow (Amharic)', type: 'string' },
      { name: 'heritageTitle', title: 'Heritage Title', type: 'string' },
      { name: 'heritageTitleAm', title: 'Heritage Title (Amharic)', type: 'string' },
      { name: 'heritageText', title: 'Heritage Text', type: 'text' },
      { name: 'heritageTextAm', title: 'Heritage Text (Amharic)', type: 'text' },
      { name: 'heritageImage', title: 'Heritage Image', type: 'image', options: { hotspot: true } },
      { name: 'storyEyebrow', title: 'Story Eyebrow', type: 'string' },
      { name: 'storyEyebrowAm', title: 'Story Eyebrow (Amharic)', type: 'string' },
      { name: 'storyTitle', title: 'Story Title', type: 'string' },
      { name: 'storyTitleAm', title: 'Story Title (Amharic)', type: 'string' },
      { name: 'storyParagraphs', title: 'Story Paragraphs', type: 'array', of: [{ type: 'text' }] },
      { name: 'storyParagraphsAm', title: 'Story Paragraphs (Amharic)', type: 'array', of: [{ type: 'text' }] },
      { name: 'storyImage', title: 'Story Image', type: 'image', options: { hotspot: true } },
      { name: 'features', title: 'Features', type: 'array', of: [{ type: 'object', fields: [{ name: 'title', type: 'string' }, { name: 'titleAm', type: 'string' }, { name: 'text', type: 'text' }, { name: 'textAm', type: 'text' }] }] },
      { name: 'featuredSections', title: 'Featured Sections', type: 'array', of: [{ type: 'object', fields: [{ name: 'title', type: 'string' }, { name: 'titleAm', type: 'string' }, { name: 'text', type: 'text' }, { name: 'textAm', type: 'text' }, { name: 'image', type: 'image' }] }] },
      { name: 'videoImage', title: 'Video Image', type: 'image', options: { hotspot: true } },
    ],
  },
  {
    name: 'aboutPage',
    title: 'About Page',
    type: 'document',
    fields: [
      { name: 'bannerImage', title: 'Banner Image', type: 'image', options: { hotspot: true } },
      { name: 'storyImage', title: 'Story Image', type: 'image', options: { hotspot: true } },
      { name: 'mission', title: 'Mission', type: 'text' },
      { name: 'missionAm', title: 'Mission (Amharic)', type: 'text' },
      { name: 'vision', title: 'Vision', type: 'text' },
      { name: 'visionAm', title: 'Vision (Amharic)', type: 'text' },
      { name: 'storyParagraphs', title: 'Story Paragraphs', type: 'array', of: [{ type: 'text' }] },
      { name: 'storyParagraphsAm', title: 'Story Paragraphs (Amharic)', type: 'array', of: [{ type: 'text' }] },
      { name: 'values', title: 'Values', type: 'array', of: [{ type: 'object', fields: [{ name: 'title', type: 'string' }, { name: 'titleAm', type: 'string' }, { name: 'description', type: 'text' }, { name: 'descriptionAm', type: 'text' }] }] },
    ],
  },
  {
    name: 'contactPage',
    title: 'Contact Page',
    type: 'document',
    fields: [
      { name: 'storeImage', title: 'Store Image', type: 'image', options: { hotspot: true } },
      { name: 'address', title: 'Address', type: 'text' },
      { name: 'email', title: 'Email', type: 'string' },
      { name: 'phone', title: 'Phone Numbers', type: 'string' },
      { name: 'mapIframe', title: 'Google Maps iframe src', type: 'url' },
      { name: 'hours', title: 'Business Hours', type: 'string' },
      { name: 'socialLinks', title: 'Social Links', type: 'array', of: [{ type: 'object', fields: [{ name: 'label', type: 'string' }, { name: 'href', type: 'url' }] }] },
    ],
  },
  {
    name: 'footer',
    title: 'Footer',
    type: 'document',
    fields: [
      { name: 'logo', title: 'Logo', type: 'image', options: { hotspot: true } },
      { name: 'description', title: 'Description', type: 'text' },
      { name: 'descriptionAm', title: 'Description (Amharic)', type: 'text' },
      { name: 'copyright', title: 'Copyright', type: 'string' },
      { name: 'copyrightAm', title: 'Copyright (Amharic)', type: 'string' },
      { name: 'links', title: 'Links', type: 'array', of: [{ type: 'object', fields: [{ name: 'label', type: 'string' }, { name: 'labelAm', type: 'string' }, { name: 'href', type: 'string' }] }] },
      { name: 'socialLinks', title: 'Social Links', type: 'array', of: [{ type: 'object', fields: [{ name: 'label', type: 'string' }, { name: 'href', type: 'url' }] }] },
      { name: 'contactInfo', title: 'Contact Info', type: 'object', fields: [{ name: 'phone', type: 'string' }, { name: 'email', type: 'string' }, { name: 'location', type: 'text' }, { name: 'hours', type: 'string' }] },
    ],
  },
  {
    name: 'websiteImage',
    title: 'Website Image',
    type: 'document',
    fields: [
      { name: 'title', title: 'Title', type: 'string' },
      { name: 'placement', title: 'Placement', type: 'string' },
      { name: 'alt', title: 'Alt Text', type: 'string' },
      { name: 'image', title: 'Image', type: 'image', options: { hotspot: true } },
    ],
  },
  {
    name: 'siteSettings',
    title: 'Site Settings',
    type: 'document',
    fields: [
      { name: 'siteTitle', title: 'Site Title', type: 'string' },
      { name: 'metaDescription', title: 'Meta Description', type: 'text' },
      { name: 'openGraphImage', title: 'Open Graph Image', type: 'image', options: { hotspot: true } },
      { name: 'structuredData', title: 'Structured Data JSON', type: 'text' },
    ],
  },
]
